version: '3'

services:
  zero:
    image: ${ZERO_IMAGE}
    build:
      context: zero
      args:
        ZERO_VERSION: ${ZERO_VERSION}
  
  app:
    ports: ['80:80']
    build:
      context: app
      args:
        BASE_IMAGE: ${ZERO_IMAGE}

  app-dev:
    image: ${ZERO_IMAGE}
    environment: # sadly fsevents/hot reloading does not work here
      NODE_ENV: development
      PORT: 8080
    ports: ['8080:8080']
    volumes: 
      - ./app/:/app/
      - yarn_cache:/usr/local/share/.cache/yarn/

volumes:
  yarn_cache: {}
